// <auto-generated />
using System;
using Hyperar.HPA.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hyperar.HPA.Data.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hyperar.HPA.Domain.Manager", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("HattrickId")
                        .HasColumnType("bigint")
                        .HasColumnName("HattrickId")
                        .HasColumnOrder(1);

                    b.Property<int>("SupporterTier")
                        .HasColumnType("int")
                        .HasColumnName("SupporterTier")
                        .HasColumnOrder(3);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar")
                        .HasColumnName("UserName")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.ToTable("Manager", (string)null);
                });

            modelBuilder.Entity("Hyperar.HPA.Domain.Token", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("TokenCreatedOn")
                        .HasColumnType("Date")
                        .HasColumnName("TokenCreatedOn")
                        .HasColumnOrder(3);

                    b.Property<DateTime>("TokenExpiresOn")
                        .HasColumnType("Date")
                        .HasColumnName("TokenExpiresOn")
                        .HasColumnOrder(4);

                    b.Property<string>("TokenSecretValue")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar")
                        .HasColumnName("TokenSecretValue")
                        .HasColumnOrder(2);

                    b.Property<string>("TokenValue")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar")
                        .HasColumnName("TokenValue")
                        .HasColumnOrder(1);

                    b.HasKey("Id");

                    b.ToTable("Token", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
