// <auto-generated />
using System;
using Hyperar.HPA.Infrastructure.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hyperar.HPA.Infrastructure.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240107200343_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hyperar.HPA.Domain.Country", b =>
                {
                    b.Property<long>("HattrickId")
                        .HasColumnType("bigint")
                        .HasColumnName("HattrickId")
                        .HasColumnOrder(0);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(4)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Code")
                        .HasColumnOrder(4);

                    b.Property<string>("CurrencyName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar")
                        .HasColumnName("CurrencyName")
                        .HasColumnOrder(2);

                    b.Property<decimal>("CurrencyRate")
                        .HasPrecision(10, 5)
                        .HasColumnType("decimal")
                        .HasColumnName("CurrencyRate")
                        .HasColumnOrder(3);

                    b.Property<string>("DateFormat")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar")
                        .HasColumnName("DateFormat")
                        .HasColumnOrder(5);

                    b.Property<long>("LeagueHattrickId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Name")
                        .HasColumnOrder(1);

                    b.Property<string>("TimeFormat")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar")
                        .HasColumnName("TimeFormat")
                        .HasColumnOrder(6);

                    b.HasKey("HattrickId");

                    b.HasIndex("LeagueHattrickId")
                        .IsUnique();

                    b.ToTable("Country", (string)null);
                });

            modelBuilder.Entity("Hyperar.HPA.Domain.League", b =>
                {
                    b.Property<long>("HattrickId")
                        .HasColumnType("bigint")
                        .HasColumnName("HattrickId")
                        .HasColumnOrder(0);

                    b.Property<long>("ActiveTeams")
                        .HasColumnType("bigint")
                        .HasColumnName("ActiveTeams")
                        .HasColumnOrder(13);

                    b.Property<long>("ActiveUsers")
                        .HasColumnType("bigint")
                        .HasColumnName("ActiveUsers")
                        .HasColumnOrder(14);

                    b.Property<string>("Continent")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Continent")
                        .HasColumnOrder(4);

                    b.Property<long>("CurrentRound")
                        .HasColumnType("bigint")
                        .HasColumnName("CurrentRound")
                        .HasColumnOrder(8);

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar")
                        .HasColumnName("EnglishName")
                        .HasColumnOrder(3);

                    b.Property<DateTime>("FifthWeeklyUpdate")
                        .HasColumnType("datetime")
                        .HasColumnName("FifthWeeklyUpdate")
                        .HasColumnOrder(25);

                    b.Property<DateTime>("FirstWeeklyUpdate")
                        .HasColumnType("datetime")
                        .HasColumnName("FirstWeeklyUpdate")
                        .HasColumnOrder(21);

                    b.Property<DateTime>("FourthWeeklyUpdate")
                        .HasColumnType("datetime")
                        .HasColumnName("FourthWeeklyUpdate")
                        .HasColumnOrder(24);

                    b.Property<long>("JuniorNationalTeamId")
                        .HasColumnType("bigint")
                        .HasColumnName("JuniorNationalTeamId")
                        .HasColumnOrder(12);

                    b.Property<long>("LanguageId")
                        .HasColumnType("bigint")
                        .HasColumnName("LanguageId")
                        .HasColumnOrder(9);

                    b.Property<string>("LanguageName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar")
                        .HasColumnName("LanguageName")
                        .HasColumnOrder(10);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Name")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("NextCupMatchDate")
                        .HasColumnType("datetime")
                        .HasColumnName("NextCupMatchDate")
                        .HasColumnOrder(19);

                    b.Property<DateTime>("NextEconomyUpdate")
                        .HasColumnType("datetime")
                        .HasColumnName("NextEconomyUpdate")
                        .HasColumnOrder(18);

                    b.Property<DateTime>("NextSeriesMatchDate")
                        .HasColumnType("datetime")
                        .HasColumnName("NextSeriesMatchDate")
                        .HasColumnOrder(20);

                    b.Property<DateTime>("NextTrainingUpdate")
                        .HasColumnType("datetime")
                        .HasColumnName("NextTrainingUpdate")
                        .HasColumnOrder(17);

                    b.Property<long>("NumberOfLevels")
                        .HasColumnType("bigint")
                        .HasColumnName("NumberOfLevels")
                        .HasColumnOrder(16);

                    b.Property<long>("Season")
                        .HasColumnType("bigint")
                        .HasColumnName("Season")
                        .HasColumnOrder(6);

                    b.Property<int>("SeasonOffset")
                        .HasColumnType("int")
                        .HasColumnName("SeasonOffset")
                        .HasColumnOrder(7);

                    b.Property<DateTime>("SecondWeeklyUpdate")
                        .HasColumnType("datetime")
                        .HasColumnName("SecondWeeklyUpdate")
                        .HasColumnOrder(22);

                    b.Property<long>("SeniorNationalTeamId")
                        .HasColumnType("bigint")
                        .HasColumnName("SeniorNationalTeamId")
                        .HasColumnOrder(11);

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar")
                        .HasColumnName("ShortName")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("ThirdWeeklyUpdate")
                        .HasColumnType("datetime")
                        .HasColumnName("ThirdWeeklyUpdate")
                        .HasColumnOrder(23);

                    b.Property<long>("WaitingUsers")
                        .HasColumnType("bigint")
                        .HasColumnName("WaitingUsers")
                        .HasColumnOrder(15);

                    b.Property<string>("Zone")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Zone")
                        .HasColumnOrder(5);

                    b.HasKey("HattrickId");

                    b.ToTable("League", (string)null);
                });

            modelBuilder.Entity("Hyperar.HPA.Domain.LeagueCup", b =>
                {
                    b.Property<long>("HattrickId")
                        .HasColumnType("bigint")
                        .HasColumnName("HattrickId")
                        .HasColumnOrder(0);

                    b.Property<long>("CurrentRound")
                        .HasColumnType("bigint")
                        .HasColumnName("CurrentRound")
                        .HasColumnOrder(5);

                    b.Property<long>("LeagueHattrickId")
                        .HasColumnType("bigint");

                    b.Property<long>("LeagueLevel")
                        .HasColumnType("bigint")
                        .HasColumnName("LeagueLevel")
                        .HasColumnOrder(2);

                    b.Property<long>("Level")
                        .HasColumnType("bigint")
                        .HasColumnName("Level")
                        .HasColumnOrder(3);

                    b.Property<long>("LevelIndex")
                        .HasColumnType("bigint")
                        .HasColumnName("LevelIndex")
                        .HasColumnOrder(4);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Name")
                        .HasColumnOrder(1);

                    b.Property<long>("RoundsLeft")
                        .HasColumnType("bigint")
                        .HasColumnName("RoundsLeft")
                        .HasColumnOrder(6);

                    b.HasKey("HattrickId");

                    b.HasIndex("LeagueHattrickId");

                    b.ToTable("LeagueCup", (string)null);
                });

            modelBuilder.Entity("Hyperar.HPA.Domain.Manager", b =>
                {
                    b.Property<long>("HattrickId")
                        .HasColumnType("bigint")
                        .HasColumnName("HattrickId")
                        .HasColumnOrder(0);

                    b.Property<byte[]>("Avatar")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("Avatar")
                        .HasColumnOrder(5);

                    b.Property<long>("CountryHattrickId")
                        .HasColumnType("bigint");

                    b.Property<string>("CurrencyName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar")
                        .HasColumnName("CurrencyName")
                        .HasColumnOrder(3);

                    b.Property<decimal>("CurrencyRate")
                        .HasPrecision(10, 5)
                        .HasColumnType("decimal")
                        .HasColumnName("CurrencyRate")
                        .HasColumnOrder(4);

                    b.Property<long>("SupporterTier")
                        .HasColumnType("bigint")
                        .HasColumnName("SupporterTier")
                        .HasColumnOrder(2);

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar")
                        .HasColumnName("UserName")
                        .HasColumnOrder(1);

                    b.HasKey("HattrickId");

                    b.HasIndex("CountryHattrickId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Manager", (string)null);
                });

            modelBuilder.Entity("Hyperar.HPA.Domain.ManagerAvatarLayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("Image")
                        .HasColumnOrder(5);

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar")
                        .HasColumnName("ImageUrl")
                        .HasColumnOrder(4);

                    b.Property<long>("Index")
                        .HasColumnType("bigint")
                        .HasColumnName("Index")
                        .HasColumnOrder(1);

                    b.Property<long>("ManagerHattrickId")
                        .HasColumnType("bigint");

                    b.Property<long>("XCoordinate")
                        .HasColumnType("bigint")
                        .HasColumnName("XCoordinate")
                        .HasColumnOrder(2);

                    b.Property<long>("YCoordinate")
                        .HasColumnType("bigint")
                        .HasColumnName("YCoordinate")
                        .HasColumnOrder(3);

                    b.HasKey("Id");

                    b.HasIndex("ManagerHattrickId");

                    b.ToTable("ManagerAvatarLayer", (string)null);
                });

            modelBuilder.Entity("Hyperar.HPA.Domain.Region", b =>
                {
                    b.Property<long>("HattrickId")
                        .HasColumnType("bigint")
                        .HasColumnName("HattrickId")
                        .HasColumnOrder(0);

                    b.Property<long>("CountryHattrickId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Name")
                        .HasColumnOrder(1);

                    b.HasKey("HattrickId");

                    b.HasIndex("CountryHattrickId");

                    b.ToTable("Region", (string)null);
                });

            modelBuilder.Entity("Hyperar.HPA.Domain.SeniorPlayer", b =>
                {
                    b.Property<long>("HattrickId")
                        .HasColumnType("bigint")
                        .HasColumnName("HattrickId")
                        .HasColumnOrder(0);

                    b.Property<long>("AgeDays")
                        .HasColumnType("bigint")
                        .HasColumnName("AgeDays")
                        .HasColumnOrder(7);

                    b.Property<long>("AgeYears")
                        .HasColumnType("bigint")
                        .HasColumnName("AgeYears")
                        .HasColumnOrder(6);

                    b.Property<long>("Aggressiveness")
                        .HasColumnType("bigint")
                        .HasColumnName("Aggressiveness")
                        .HasColumnOrder(16);

                    b.Property<long>("Agreeability")
                        .HasColumnType("bigint")
                        .HasColumnName("Agreeability")
                        .HasColumnOrder(15);

                    b.Property<long>("BookingStatus")
                        .HasColumnType("bigint")
                        .HasColumnName("BookingStatus")
                        .HasColumnOrder(31);

                    b.Property<long>("CareerGoals")
                        .HasColumnType("bigint")
                        .HasColumnName("CareerGoals")
                        .HasColumnOrder(25);

                    b.Property<long>("CareerHattricks")
                        .HasColumnType("bigint")
                        .HasColumnName("CareerHattricks")
                        .HasColumnOrder(26);

                    b.Property<long>("Category")
                        .HasColumnType("bigint")
                        .HasColumnName("Category")
                        .HasColumnOrder(33);

                    b.Property<long>("CountryHattrickId")
                        .HasColumnType("bigint");

                    b.Property<long>("CurrentSeasonCupGoals")
                        .HasColumnType("bigint")
                        .HasColumnName("CurrentSeasonCupGoals")
                        .HasColumnOrder(23);

                    b.Property<long>("CurrentSeasonFriendlyGoals")
                        .HasColumnType("bigint")
                        .HasColumnName("CurrentSeasonFriendlyGoals")
                        .HasColumnOrder(24);

                    b.Property<long>("CurrentSeasonLeagueGoals")
                        .HasColumnType("bigint")
                        .HasColumnName("CurrentSeasonLeagueGoals")
                        .HasColumnOrder(22);

                    b.Property<bool>("EnrolledOnNationalTeam")
                        .HasColumnType("bit")
                        .HasColumnName("EnrolledOnNationalTeam")
                        .HasColumnOrder(21);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar")
                        .HasColumnName("FirstName")
                        .HasColumnOrder(1);

                    b.Property<long>("GoalsOnTeam")
                        .HasColumnType("bigint")
                        .HasColumnName("GoalsOnTeam")
                        .HasColumnOrder(27);

                    b.Property<bool>("HasMotherClubBonus")
                        .HasColumnType("bit")
                        .HasColumnName("HasMotherClubBonus")
                        .HasColumnOrder(12);

                    b.Property<int>("Health")
                        .HasColumnType("int")
                        .HasColumnName("Health")
                        .HasColumnOrder(32);

                    b.Property<long>("Honesty")
                        .HasColumnType("bigint")
                        .HasColumnName("Honesty")
                        .HasColumnOrder(17);

                    b.Property<bool>("IsCoach")
                        .HasColumnType("bit")
                        .HasColumnName("IsCoach")
                        .HasColumnOrder(5);

                    b.Property<bool>("IsForeign")
                        .HasColumnType("bit")
                        .HasColumnName("IsForeign")
                        .HasColumnOrder(14);

                    b.Property<bool>("IsTransferListed")
                        .HasColumnType("bit")
                        .HasColumnName("IsTransferListed")
                        .HasColumnOrder(20);

                    b.Property<DateTime>("JoinedTeamOn")
                        .HasColumnType("datetime")
                        .HasColumnName("JoinedTeamOn")
                        .HasColumnOrder(8);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar")
                        .HasColumnName("LastName")
                        .HasColumnOrder(3);

                    b.Property<long>("Leadership")
                        .HasColumnType("bigint")
                        .HasColumnName("Leadership")
                        .HasColumnOrder(18);

                    b.Property<long>("MatchesOnTeam")
                        .HasColumnType("bigint")
                        .HasColumnName("MatchesOnTeam")
                        .HasColumnOrder(28);

                    b.Property<string>("NickName")
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar")
                        .HasColumnName("NickName")
                        .HasColumnOrder(2);

                    b.Property<string>("Notes")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Notes")
                        .HasColumnOrder(9);

                    b.Property<long>("Salary")
                        .HasColumnType("bigint")
                        .HasColumnName("Salary")
                        .HasColumnOrder(13);

                    b.Property<long>("SeniorNationalTeamCaps")
                        .HasColumnType("bigint")
                        .HasColumnName("SeniorNationalTeamCaps")
                        .HasColumnOrder(29);

                    b.Property<long>("SeniorTeamHattrickId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ShirtNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("ShirtNumber")
                        .HasColumnOrder(4);

                    b.Property<long>("Specialty")
                        .HasColumnType("bigint")
                        .HasColumnName("Specialty")
                        .HasColumnOrder(19);

                    b.Property<string>("Statement")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Statement")
                        .HasColumnOrder(10);

                    b.Property<long>("TotalSkillIndex")
                        .HasColumnType("bigint")
                        .HasColumnName("TotalSkillIndex")
                        .HasColumnOrder(11);

                    b.Property<long>("YouthNationalTeamCaps")
                        .HasColumnType("bigint")
                        .HasColumnName("YouthNationalTeamCaps")
                        .HasColumnOrder(30);

                    b.HasKey("HattrickId");

                    b.HasIndex("CountryHattrickId");

                    b.HasIndex("SeniorTeamHattrickId");

                    b.ToTable("SeniorPlayer", (string)null);
                });

            modelBuilder.Entity("Hyperar.HPA.Domain.SeniorPlayerSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("Defending")
                        .HasColumnType("bigint")
                        .HasColumnName("Defending")
                        .HasColumnOrder(5);

                    b.Property<long>("Experience")
                        .HasColumnType("bigint")
                        .HasColumnName("Experience")
                        .HasColumnOrder(11);

                    b.Property<long>("Form")
                        .HasColumnType("bigint")
                        .HasColumnName("Form")
                        .HasColumnOrder(2);

                    b.Property<long>("Keeper")
                        .HasColumnType("bigint")
                        .HasColumnName("Keeper")
                        .HasColumnOrder(4);

                    b.Property<long>("Loyalty")
                        .HasColumnType("bigint")
                        .HasColumnName("Loyalty")
                        .HasColumnOrder(12);

                    b.Property<long>("Passing")
                        .HasColumnType("bigint")
                        .HasColumnName("Passing")
                        .HasColumnOrder(8);

                    b.Property<long>("Playmaking")
                        .HasColumnType("bigint")
                        .HasColumnName("Playmaking")
                        .HasColumnOrder(6);

                    b.Property<long>("Scoring")
                        .HasColumnType("bigint")
                        .HasColumnName("Scoring")
                        .HasColumnOrder(9);

                    b.Property<long>("SeniorPlayerHattrickId")
                        .HasColumnType("bigint");

                    b.Property<long>("SetPieces")
                        .HasColumnType("bigint")
                        .HasColumnName("SetPieces")
                        .HasColumnOrder(10);

                    b.Property<long>("Stamina")
                        .HasColumnType("bigint")
                        .HasColumnName("Stamina")
                        .HasColumnOrder(3);

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime")
                        .HasColumnName("UpdatedOn")
                        .HasColumnOrder(1);

                    b.Property<long>("Winger")
                        .HasColumnType("bigint")
                        .HasColumnName("Winger")
                        .HasColumnOrder(7);

                    b.HasKey("Id");

                    b.HasIndex("SeniorPlayerHattrickId");

                    b.ToTable("SeniorPlayerSkill", (string)null);
                });

            modelBuilder.Entity("Hyperar.HPA.Domain.SeniorTeam", b =>
                {
                    b.Property<long>("HattrickId")
                        .HasColumnType("bigint")
                        .HasColumnName("HattrickId")
                        .HasColumnOrder(0);

                    b.Property<byte[]>("AlternativeMatchKit")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("AlternativeMatchKit")
                        .HasColumnOrder(22);

                    b.Property<string>("AlternativeMatchKitUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar")
                        .HasColumnName("AlternativeMatchKitUrl")
                        .HasColumnOrder(19);

                    b.Property<long>("CoachPlayerId")
                        .HasColumnType("bigint")
                        .HasColumnName("CoachPlayerId")
                        .HasColumnOrder(5);

                    b.Property<DateTime>("FoundedOn")
                        .HasColumnType("datetime")
                        .HasColumnName("FoundedOn")
                        .HasColumnOrder(4);

                    b.Property<long>("GlobalRanking")
                        .HasColumnType("bigint")
                        .HasColumnName("GlobalRanking")
                        .HasColumnOrder(7);

                    b.Property<bool>("IsPlayingCup")
                        .HasColumnType("bit")
                        .HasColumnName("IsPlayingCup")
                        .HasColumnOrder(6);

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit")
                        .HasColumnName("IsPrimary")
                        .HasColumnOrder(3);

                    b.Property<long>("LeagueHattrickId")
                        .HasColumnType("bigint");

                    b.Property<long>("LeagueRanking")
                        .HasColumnType("bigint")
                        .HasColumnName("LeagueRanking")
                        .HasColumnOrder(8);

                    b.Property<byte[]>("Logo")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("Logo")
                        .HasColumnOrder(20);

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(1024)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar")
                        .HasColumnName("LogoUrl")
                        .HasColumnOrder(17);

                    b.Property<long>("ManagerHattrickId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("MatchKit")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("MatchKit")
                        .HasColumnOrder(21);

                    b.Property<string>("MatchKitUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar")
                        .HasColumnName("MatchKitUrl")
                        .HasColumnOrder(18);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Name")
                        .HasColumnOrder(1);

                    b.Property<long>("PowerRanking")
                        .HasColumnType("bigint")
                        .HasColumnName("PowerRanking")
                        .HasColumnOrder(10);

                    b.Property<long>("RegionHattrickId")
                        .HasColumnType("bigint");

                    b.Property<long>("RegionRanking")
                        .HasColumnType("bigint")
                        .HasColumnName("RegionRanking")
                        .HasColumnOrder(9);

                    b.Property<long>("SeniorSeriesDivision")
                        .HasColumnType("bigint")
                        .HasColumnName("SeniorSeriesDivision")
                        .HasColumnOrder(16);

                    b.Property<long>("SeniorSeriesHattrickId")
                        .HasColumnType("bigint")
                        .HasColumnName("SeniorSeriesHattrickId")
                        .HasColumnOrder(14);

                    b.Property<string>("SeniorSeriesName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar")
                        .HasColumnName("SeniorSeriesName")
                        .HasColumnOrder(15);

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar")
                        .HasColumnName("ShortName")
                        .HasColumnOrder(2);

                    b.Property<long>("TeamRank")
                        .HasColumnType("bigint")
                        .HasColumnName("TeamRank")
                        .HasColumnOrder(11);

                    b.Property<long>("UndefeatedStreak")
                        .HasColumnType("bigint")
                        .HasColumnName("UndefeatedStreak")
                        .HasColumnOrder(12);

                    b.Property<long>("WinStreak")
                        .HasColumnType("bigint")
                        .HasColumnName("WinStreak")
                        .HasColumnOrder(13);

                    b.HasKey("HattrickId");

                    b.HasIndex("LeagueHattrickId");

                    b.HasIndex("ManagerHattrickId");

                    b.HasIndex("RegionHattrickId");

                    b.ToTable("SeniorTeam", (string)null);
                });

            modelBuilder.Entity("Hyperar.HPA.Domain.SeniorTeamArena", b =>
                {
                    b.Property<long>("HattrickId")
                        .HasColumnType("bigint")
                        .HasColumnName("HattrickId")
                        .HasColumnOrder(0);

                    b.Property<long>("BasicSeatCapacity")
                        .HasColumnType("bigint")
                        .HasColumnName("BasicSeatCapacity")
                        .HasColumnOrder(4);

                    b.Property<DateTime>("BuiltOn")
                        .HasColumnType("datetime")
                        .HasColumnName("BuiltOn")
                        .HasColumnOrder(2);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Name")
                        .HasColumnOrder(1);

                    b.Property<long>("RoofSeatCapacity")
                        .HasColumnType("bigint")
                        .HasColumnName("RoofSeatCapacity")
                        .HasColumnOrder(5);

                    b.Property<long>("SeniorTeamHattrickId")
                        .HasColumnType("bigint");

                    b.Property<long>("TerracesCapacity")
                        .HasColumnType("bigint")
                        .HasColumnName("TerracesCapacity")
                        .HasColumnOrder(3);

                    b.Property<long>("TotalCapacity")
                        .HasColumnType("bigint")
                        .HasColumnName("TotalCapacity")
                        .HasColumnOrder(7);

                    b.Property<long>("VipLoungeCapacity")
                        .HasColumnType("bigint")
                        .HasColumnName("VipLoungeCapacity")
                        .HasColumnOrder(6);

                    b.HasKey("HattrickId");

                    b.HasIndex("SeniorTeamHattrickId")
                        .IsUnique();

                    b.ToTable("SeniorTeamArena", (string)null);
                });

            modelBuilder.Entity("Hyperar.HPA.Domain.SeniorTeamOverviewMatch", b =>
                {
                    b.Property<long>("HattrickId")
                        .HasColumnType("bigint")
                        .HasColumnName("HattrickId")
                        .HasColumnOrder(0);

                    b.Property<long?>("AwayGoals")
                        .HasColumnType("bigint")
                        .HasColumnName("AwayGoals")
                        .HasColumnOrder(8);

                    b.Property<long>("AwayTeamHattrickId")
                        .HasColumnType("bigint")
                        .HasColumnName("AwayTeamHattrickId")
                        .HasColumnOrder(5);

                    b.Property<string>("AwayTeamName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar")
                        .HasColumnName("AwayTeamName")
                        .HasColumnOrder(6);

                    b.Property<string>("AwayTeamShortName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar")
                        .HasColumnName("AwayTeamShortName")
                        .HasColumnOrder(7);

                    b.Property<long?>("CompetitionId")
                        .HasColumnType("bigint")
                        .HasColumnName("CompetitionId")
                        .HasColumnOrder(11);

                    b.Property<long?>("HomeGoals")
                        .HasColumnType("bigint")
                        .HasColumnName("HomeGoals")
                        .HasColumnOrder(4);

                    b.Property<long>("HomeTeamHattrickId")
                        .HasColumnType("bigint")
                        .HasColumnName("HomeTeamHattrickId")
                        .HasColumnOrder(1);

                    b.Property<string>("HomeTeamName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar")
                        .HasColumnName("HomeTeamName")
                        .HasColumnOrder(2);

                    b.Property<string>("HomeTeamShortName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar")
                        .HasColumnName("HomeTeamShortName")
                        .HasColumnOrder(3);

                    b.Property<long>("SeniorTeamHattrickId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("StartsOn")
                        .HasColumnType("datetime")
                        .HasColumnName("StartsOn")
                        .HasColumnOrder(9);

                    b.Property<long>("Status")
                        .HasColumnType("bigint")
                        .HasColumnName("Status")
                        .HasColumnOrder(12);

                    b.Property<long>("Type")
                        .HasColumnType("bigint")
                        .HasColumnName("Type")
                        .HasColumnOrder(10);

                    b.HasKey("HattrickId");

                    b.HasIndex("SeniorTeamHattrickId");

                    b.ToTable("SeniorTeamOverviewMatch", (string)null);
                });

            modelBuilder.Entity("Hyperar.HPA.Domain.Token", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime")
                        .HasColumnName("CreatedOn")
                        .HasColumnOrder(3);

                    b.Property<DateTime>("ExpiresOn")
                        .HasColumnType("datetime")
                        .HasColumnName("ExpiresOn")
                        .HasColumnOrder(4);

                    b.Property<string>("SecretValue")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar")
                        .HasColumnName("SecretValue")
                        .HasColumnOrder(2);

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Value")
                        .HasColumnOrder(1);

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Token", (string)null);
                });

            modelBuilder.Entity("Hyperar.HPA.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("LastDownloadDate")
                        .HasColumnType("datetime")
                        .HasColumnName("LastDownloadDate")
                        .HasColumnOrder(1);

                    b.HasKey("Id");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("Hyperar.HPA.Domain.Country", b =>
                {
                    b.HasOne("Hyperar.HPA.Domain.League", "League")
                        .WithOne("Country")
                        .HasForeignKey("Hyperar.HPA.Domain.Country", "LeagueHattrickId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("League");
                });

            modelBuilder.Entity("Hyperar.HPA.Domain.LeagueCup", b =>
                {
                    b.HasOne("Hyperar.HPA.Domain.League", "League")
                        .WithMany("Cups")
                        .HasForeignKey("LeagueHattrickId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("League");
                });

            modelBuilder.Entity("Hyperar.HPA.Domain.Manager", b =>
                {
                    b.HasOne("Hyperar.HPA.Domain.Country", "Country")
                        .WithMany("Managers")
                        .HasForeignKey("CountryHattrickId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Hyperar.HPA.Domain.User", "User")
                        .WithOne("Manager")
                        .HasForeignKey("Hyperar.HPA.Domain.Manager", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Hyperar.HPA.Domain.ManagerAvatarLayer", b =>
                {
                    b.HasOne("Hyperar.HPA.Domain.Manager", "Manager")
                        .WithMany("AvatarLayers")
                        .HasForeignKey("ManagerHattrickId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("Hyperar.HPA.Domain.Region", b =>
                {
                    b.HasOne("Hyperar.HPA.Domain.Country", "Country")
                        .WithMany("Regions")
                        .HasForeignKey("CountryHattrickId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Hyperar.HPA.Domain.SeniorPlayer", b =>
                {
                    b.HasOne("Hyperar.HPA.Domain.Country", "Country")
                        .WithMany("SeniorPlayers")
                        .HasForeignKey("CountryHattrickId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hyperar.HPA.Domain.SeniorTeam", "SeniorTeam")
                        .WithMany("SeniorPlayers")
                        .HasForeignKey("SeniorTeamHattrickId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("SeniorTeam");
                });

            modelBuilder.Entity("Hyperar.HPA.Domain.SeniorPlayerSkill", b =>
                {
                    b.HasOne("Hyperar.HPA.Domain.SeniorPlayer", "SeniorPlayer")
                        .WithMany("SeniorPlayerSkills")
                        .HasForeignKey("SeniorPlayerHattrickId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("SeniorPlayer");
                });

            modelBuilder.Entity("Hyperar.HPA.Domain.SeniorTeam", b =>
                {
                    b.HasOne("Hyperar.HPA.Domain.League", "League")
                        .WithMany("SeniorTeams")
                        .HasForeignKey("LeagueHattrickId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hyperar.HPA.Domain.Manager", "Manager")
                        .WithMany("SeniorTeams")
                        .HasForeignKey("ManagerHattrickId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hyperar.HPA.Domain.Region", "Region")
                        .WithMany("SeniorTeams")
                        .HasForeignKey("RegionHattrickId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("League");

                    b.Navigation("Manager");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("Hyperar.HPA.Domain.SeniorTeamArena", b =>
                {
                    b.HasOne("Hyperar.HPA.Domain.SeniorTeam", "SeniorTeam")
                        .WithOne("SeniorTeamArena")
                        .HasForeignKey("Hyperar.HPA.Domain.SeniorTeamArena", "SeniorTeamHattrickId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SeniorTeam");
                });

            modelBuilder.Entity("Hyperar.HPA.Domain.SeniorTeamOverviewMatch", b =>
                {
                    b.HasOne("Hyperar.HPA.Domain.SeniorTeam", "SeniorTeam")
                        .WithMany("OverviewMatches")
                        .HasForeignKey("SeniorTeamHattrickId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("SeniorTeam");
                });

            modelBuilder.Entity("Hyperar.HPA.Domain.Token", b =>
                {
                    b.HasOne("Hyperar.HPA.Domain.User", "User")
                        .WithOne("Token")
                        .HasForeignKey("Hyperar.HPA.Domain.Token", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Hyperar.HPA.Domain.Country", b =>
                {
                    b.Navigation("Managers");

                    b.Navigation("Regions");

                    b.Navigation("SeniorPlayers");
                });

            modelBuilder.Entity("Hyperar.HPA.Domain.League", b =>
                {
                    b.Navigation("Country");

                    b.Navigation("Cups");

                    b.Navigation("SeniorTeams");
                });

            modelBuilder.Entity("Hyperar.HPA.Domain.Manager", b =>
                {
                    b.Navigation("AvatarLayers");

                    b.Navigation("SeniorTeams");
                });

            modelBuilder.Entity("Hyperar.HPA.Domain.Region", b =>
                {
                    b.Navigation("SeniorTeams");
                });

            modelBuilder.Entity("Hyperar.HPA.Domain.SeniorPlayer", b =>
                {
                    b.Navigation("SeniorPlayerSkills");
                });

            modelBuilder.Entity("Hyperar.HPA.Domain.SeniorTeam", b =>
                {
                    b.Navigation("OverviewMatches");

                    b.Navigation("SeniorPlayers");

                    b.Navigation("SeniorTeamArena");
                });

            modelBuilder.Entity("Hyperar.HPA.Domain.User", b =>
                {
                    b.Navigation("Manager");

                    b.Navigation("Token");
                });
#pragma warning restore 612, 618
        }
    }
}
