//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hyperar.HPA.Globalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hyperar.HPA.Globalization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        public static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} years and {1} days, next birthday: {2}.
        /// </summary>
        public static string AgeAndNextBirthDayMask {
            get {
                return ResourceManager.GetString("AgeAndNextBirthDayMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} years and {1} day(s).
        /// </summary>
        public static string AgeMask {
            get {
                return ResourceManager.GetString("AgeMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggressiveness.
        /// </summary>
        public static string Aggressiveness {
            get {
                return ResourceManager.GetString("Aggressiveness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to balanced.
        /// </summary>
        public static string AggressivenessLevel_Balanced {
            get {
                return ResourceManager.GetString("AggressivenessLevel_Balanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to calm.
        /// </summary>
        public static string AggressivenessLevel_Calm {
            get {
                return ResourceManager.GetString("AggressivenessLevel_Calm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fiery.
        /// </summary>
        public static string AggressivenessLevel_Fiery {
            get {
                return ResourceManager.GetString("AggressivenessLevel_Fiery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to temperamental.
        /// </summary>
        public static string AggressivenessLevel_Temperamental {
            get {
                return ResourceManager.GetString("AggressivenessLevel_Temperamental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tranquil.
        /// </summary>
        public static string AggressivenessLevel_Tranquil {
            get {
                return ResourceManager.GetString("AggressivenessLevel_Tranquil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unstable.
        /// </summary>
        public static string AggressivenessLevel_Unstable {
            get {
                return ResourceManager.GetString("AggressivenessLevel_Unstable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agreeability.
        /// </summary>
        public static string Agreeability {
            get {
                return ResourceManager.GetString("Agreeability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to beloved team member.
        /// </summary>
        public static string AgreeabilityLevel_BelovedTeamMember {
            get {
                return ResourceManager.GetString("AgreeabilityLevel_BelovedTeamMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to controversial person.
        /// </summary>
        public static string AgreeabilityLevel_ControversialPerson {
            get {
                return ResourceManager.GetString("AgreeabilityLevel_ControversialPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nasty fellow.
        /// </summary>
        public static string AgreeabilityLevel_NastyFellow {
            get {
                return ResourceManager.GetString("AgreeabilityLevel_NastyFellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pleasant guy.
        /// </summary>
        public static string AgreeabilityLevel_PleasantGuy {
            get {
                return ResourceManager.GetString("AgreeabilityLevel_PleasantGuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to popular guy.
        /// </summary>
        public static string AgreeabilityLevel_PopularGuy {
            get {
                return ResourceManager.GetString("AgreeabilityLevel_PopularGuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sympathetic guy.
        /// </summary>
        public static string AgreeabilityLevel_SympatheticGuy {
            get {
                return ResourceManager.GetString("AgreeabilityLevel_SympatheticGuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization.
        /// </summary>
        public static string Authorization {
            get {
                return ResourceManager.GetString("Authorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorize.
        /// </summary>
        public static string Authorize {
            get {
                return ResourceManager.GetString("Authorize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorized.
        /// </summary>
        public static string Authorized {
            get {
                return ResourceManager.GetString("Authorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once you have pasted the Verification Code, click on &apos;Authorize&apos;..
        /// </summary>
        public static string AuthorizeMessage {
            get {
                return ResourceManager.GetString("AuthorizeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookings.
        /// </summary>
        public static string Bookings {
            get {
                return ResourceManager.GetString("Bookings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No bookings.
        /// </summary>
        public static string BookingStatus_NoBookings {
            get {
                return ResourceManager.GetString("BookingStatus_NoBookings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One booking.
        /// </summary>
        public static string BookingStatus_OneYellowCard {
            get {
                return ResourceManager.GetString("BookingStatus_OneYellowCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspended.
        /// </summary>
        public static string BookingStatus_Suspended {
            get {
                return ResourceManager.GetString("BookingStatus_Suspended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two bookings.
        /// </summary>
        public static string BookingStatus_TwoYellowCards {
            get {
                return ResourceManager.GetString("BookingStatus_TwoYellowCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bruised.
        /// </summary>
        public static string Brusied {
            get {
                return ResourceManager.GetString("Brusied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Career Goals.
        /// </summary>
        public static string CareerGoals {
            get {
                return ResourceManager.GetString("CareerGoals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Career Hattricks.
        /// </summary>
        public static string CareerHattricks {
            get {
                return ResourceManager.GetString("CareerHattricks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare.
        /// </summary>
        public static string Compare {
            get {
                return ResourceManager.GetString("Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once you have logged in into your Hattrick account, you will be provided with a Verification Code. Copy the code and paste it below, making sure there&apos;s no blank spaces at the beggining or the end of the code..
        /// </summary>
        public static string CopyAndPasteVerificationCodeMessage {
            get {
                return ResourceManager.GetString("CopyAndPasteVerificationCodeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country:.
        /// </summary>
        public static string CountryLabel {
            get {
                return ResourceManager.GetString("CountryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cup Goals.
        /// </summary>
        public static string CupGoals {
            get {
                return ResourceManager.GetString("CupGoals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De-authorize.
        /// </summary>
        public static string Deauthorize {
            get {
                return ResourceManager.GetString("Deauthorize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If at any point you want to de-authorize Hattrick Pro Assistant, you can do so by clicking on &apos;De-authorize&apos;..
        /// </summary>
        public static string DeAuthorizeMessage {
            get {
                return ResourceManager.GetString("DeAuthorizeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defending.
        /// </summary>
        public static string Defending {
            get {
                return ResourceManager.GetString("Defending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled.
        /// </summary>
        public static string DownloadTaskStatus_Canceled {
            get {
                return ResourceManager.GetString("DownloadTaskStatus_Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string DownloadTaskStatus_Done {
            get {
                return ResourceManager.GetString("DownloadTaskStatus_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading.
        /// </summary>
        public static string DownloadTaskStatus_Downloading {
            get {
                return ResourceManager.GetString("DownloadTaskStatus_Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string DownloadTaskStatus_Error {
            get {
                return ResourceManager.GetString("DownloadTaskStatus_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string DownloadTaskStatus_Pending {
            get {
                return ResourceManager.GetString("DownloadTaskStatus_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing.
        /// </summary>
        public static string DownloadTaskStatus_Processing {
            get {
                return ResourceManager.GetString("DownloadTaskStatus_Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving.
        /// </summary>
        public static string DownloadTaskStatus_Saving {
            get {
                return ResourceManager.GetString("DownloadTaskStatus_Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience.
        /// </summary>
        public static string Experience {
            get {
                return ResourceManager.GetString("Experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form.
        /// </summary>
        public static string Form {
            get {
                return ResourceManager.GetString("Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friendly Goals.
        /// </summary>
        public static string FriendlyGoals {
            get {
                return ResourceManager.GetString("FriendlyGoals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals On Team.
        /// </summary>
        public static string GoalsOnTeam {
            get {
                return ResourceManager.GetString("GoalsOnTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health.
        /// </summary>
        public static string Health {
            get {
                return ResourceManager.GetString("Health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Healthy.
        /// </summary>
        public static string Healthy {
            get {
                return ResourceManager.GetString("Healthy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Honesty.
        /// </summary>
        public static string Honesty {
            get {
                return ResourceManager.GetString("Honesty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dishonest.
        /// </summary>
        public static string HonestyLevel_Dishonest {
            get {
                return ResourceManager.GetString("HonestyLevel_Dishonest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to honest.
        /// </summary>
        public static string HonestyLevel_Honest {
            get {
                return ResourceManager.GetString("HonestyLevel_Honest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to infamous.
        /// </summary>
        public static string HonestyLevel_Infamous {
            get {
                return ResourceManager.GetString("HonestyLevel_Infamous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to righteous.
        /// </summary>
        public static string HonestyLevel_Righteous {
            get {
                return ResourceManager.GetString("HonestyLevel_Righteous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to saintly.
        /// </summary>
        public static string HonestyLevel_Saintly {
            get {
                return ResourceManager.GetString("HonestyLevel_Saintly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to upright.
        /// </summary>
        public static string HonestyLevel_Upright {
            get {
                return ResourceManager.GetString("HonestyLevel_Upright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Injured: {0} week(s).
        /// </summary>
        public static string InjuredWeeks {
            get {
                return ResourceManager.GetString("InjuredWeeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keeper.
        /// </summary>
        public static string Keeper {
            get {
                return ResourceManager.GetString("Keeper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lastname.
        /// </summary>
        public static string Lastname {
            get {
                return ResourceManager.GetString("Lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leadership.
        /// </summary>
        public static string Leadership {
            get {
                return ResourceManager.GetString("Leadership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to League.
        /// </summary>
        public static string League {
            get {
                return ResourceManager.GetString("League", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to League Goals.
        /// </summary>
        public static string LeagueGoals {
            get {
                return ResourceManager.GetString("LeagueGoals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to League:.
        /// </summary>
        public static string LeagueLabel {
            get {
                return ResourceManager.GetString("LeagueLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loyalty.
        /// </summary>
        public static string Loyalty {
            get {
                return ResourceManager.GetString("Loyalty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager.
        /// </summary>
        public static string Manager {
            get {
                return ResourceManager.GetString("Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matches.
        /// </summary>
        public static string Matches {
            get {
                return ResourceManager.GetString("Matches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matches On Team.
        /// </summary>
        public static string MatchesOnTeam {
            get {
                return ResourceManager.GetString("MatchesOnTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MC Bonus.
        /// </summary>
        public static string MotherclubBonus {
            get {
                return ResourceManager.GetString("MotherclubBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nickname.
        /// </summary>
        public static string Nickname {
            get {
                return ResourceManager.GetString("Nickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Authorized.
        /// </summary>
        public static string NotAuthorized {
            get {
                return ResourceManager.GetString("NotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Authorization Web Page.
        /// </summary>
        public static string OpenAuthorizationWebPage {
            get {
                return ResourceManager.GetString("OpenAuthorizationWebPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to use Hattrick Pro Assistant, you have to authorize it first. Click on &apos;Open Authorization Web Page&apos; to begin the authorization process..
        /// </summary>
        public static string OpenAuthorizationWebPageMessage {
            get {
                return ResourceManager.GetString("OpenAuthorizationWebPageMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        public static string Parameters {
            get {
                return ResourceManager.GetString("Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passing.
        /// </summary>
        public static string Passing {
            get {
                return ResourceManager.GetString("Passing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A {0} who is {1} and {2}.
        ///Has {3} experience and {4} leadership. Has {5} loyalty..
        /// </summary>
        public static string PlayerDetailDescription {
            get {
                return ResourceManager.GetString("PlayerDetailDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players.
        /// </summary>
        public static string Players {
            get {
                return ResourceManager.GetString("Players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playmaking.
        /// </summary>
        public static string Playmaking {
            get {
                return ResourceManager.GetString("Playmaking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Matches.
        /// </summary>
        public static string RecentMatches {
            get {
                return ResourceManager.GetString("RecentMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region:.
        /// </summary>
        public static string RegionLabel {
            get {
                return ResourceManager.GetString("RegionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary.
        /// </summary>
        public static string Salary {
            get {
                return ResourceManager.GetString("Salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scoring.
        /// </summary>
        public static string Scoring {
            get {
                return ResourceManager.GetString("Scoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Team.
        /// </summary>
        public static string SelectTeam {
            get {
                return ResourceManager.GetString("SelectTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Pieces.
        /// </summary>
        public static string SetPieces {
            get {
                return ResourceManager.GetString("SetPieces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #.
        /// </summary>
        public static string ShirtNumber {
            get {
                return ResourceManager.GetString("ShirtNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to brilliant.
        /// </summary>
        public static string SkillLevel_Brilliant {
            get {
                return ResourceManager.GetString("SkillLevel_Brilliant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to disastrous.
        /// </summary>
        public static string SkillLevel_Disastrous {
            get {
                return ResourceManager.GetString("SkillLevel_Disastrous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to divine.
        /// </summary>
        public static string SkillLevel_Divine {
            get {
                return ResourceManager.GetString("SkillLevel_Divine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to excellent.
        /// </summary>
        public static string SkillLevel_Excellent {
            get {
                return ResourceManager.GetString("SkillLevel_Excellent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to extra-terrestrial.
        /// </summary>
        public static string SkillLevel_ExtraTerrestrial {
            get {
                return ResourceManager.GetString("SkillLevel_ExtraTerrestrial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to formidable.
        /// </summary>
        public static string SkillLevel_Formidable {
            get {
                return ResourceManager.GetString("SkillLevel_Formidable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inadequate.
        /// </summary>
        public static string SkillLevel_Inadequate {
            get {
                return ResourceManager.GetString("SkillLevel_Inadequate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to magical.
        /// </summary>
        public static string SkillLevel_Magical {
            get {
                return ResourceManager.GetString("SkillLevel_Magical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to magnificent.
        /// </summary>
        public static string SkillLevel_Magnificent {
            get {
                return ResourceManager.GetString("SkillLevel_Magnificent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mythical.
        /// </summary>
        public static string SkillLevel_Mythical {
            get {
                return ResourceManager.GetString("SkillLevel_Mythical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to non-existent.
        /// </summary>
        public static string SkillLevel_NonExistent {
            get {
                return ResourceManager.GetString("SkillLevel_NonExistent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to outstanding.
        /// </summary>
        public static string SkillLevel_Outstanding {
            get {
                return ResourceManager.GetString("SkillLevel_Outstanding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to passable.
        /// </summary>
        public static string SkillLevel_Passable {
            get {
                return ResourceManager.GetString("SkillLevel_Passable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to poor.
        /// </summary>
        public static string SkillLevel_Poor {
            get {
                return ResourceManager.GetString("SkillLevel_Poor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to solid.
        /// </summary>
        public static string SkillLevel_Solid {
            get {
                return ResourceManager.GetString("SkillLevel_Solid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to supernatural.
        /// </summary>
        public static string SkillLevel_Supernatural {
            get {
                return ResourceManager.GetString("SkillLevel_Supernatural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to titanic.
        /// </summary>
        public static string SkillLevel_Titanic {
            get {
                return ResourceManager.GetString("SkillLevel_Titanic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to utopian.
        /// </summary>
        public static string SkillLevel_Utopian {
            get {
                return ResourceManager.GetString("SkillLevel_Utopian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to weak.
        /// </summary>
        public static string SkillLevel_Weak {
            get {
                return ResourceManager.GetString("SkillLevel_Weak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to world class.
        /// </summary>
        public static string SkillLevel_WorldClass {
            get {
                return ResourceManager.GetString("SkillLevel_WorldClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wretched.
        /// </summary>
        public static string SkillLevel_Wretched {
            get {
                return ResourceManager.GetString("SkillLevel_Wretched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialty.
        /// </summary>
        public static string Specialty {
            get {
                return ResourceManager.GetString("Specialty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head Specialist.
        /// </summary>
        public static string Specialty_HeadSpecialist {
            get {
                return ResourceManager.GetString("Specialty_HeadSpecialist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powerful.
        /// </summary>
        public static string Specialty_Powerful {
            get {
                return ResourceManager.GetString("Specialty_Powerful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick.
        /// </summary>
        public static string Specialty_Quick {
            get {
                return ResourceManager.GetString("Specialty_Quick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resilient.
        /// </summary>
        public static string Specialty_Resilient {
            get {
                return ResourceManager.GetString("Specialty_Resilient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string Specialty_Support {
            get {
                return ResourceManager.GetString("Specialty_Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical.
        /// </summary>
        public static string Specialty_Technical {
            get {
                return ResourceManager.GetString("Specialty_Technical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpredictable.
        /// </summary>
        public static string Specialty_Unpredictable {
            get {
                return ResourceManager.GetString("Specialty_Unpredictable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stamina.
        /// </summary>
        public static string Stamina {
            get {
                return ResourceManager.GetString("Stamina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 1.
        /// </summary>
        public static string StepOne {
            get {
                return ResourceManager.GetString("StepOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 3.
        /// </summary>
        public static string StepThree {
            get {
                return ResourceManager.GetString("StepThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 2.
        /// </summary>
        public static string StepTwo {
            get {
                return ResourceManager.GetString("StepTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supporter:.
        /// </summary>
        public static string SupporterLabel {
            get {
                return ResourceManager.GetString("SupporterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diamond.
        /// </summary>
        public static string SupporterTier_Diamond {
            get {
                return ResourceManager.GetString("SupporterTier_Diamond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold.
        /// </summary>
        public static string SupporterTier_Gold {
            get {
                return ResourceManager.GetString("SupporterTier_Gold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Supporter.
        /// </summary>
        public static string SupporterTier_NoSupporter {
            get {
                return ResourceManager.GetString("SupporterTier_NoSupporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platinum.
        /// </summary>
        public static string SupporterTier_Platinum {
            get {
                return ResourceManager.GetString("SupporterTier_Platinum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silver.
        /// </summary>
        public static string SupporterTier_Silver {
            get {
                return ResourceManager.GetString("SupporterTier_Silver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        public static string Team {
            get {
                return ResourceManager.GetString("Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team:.
        /// </summary>
        public static string TeamLabel {
            get {
                return ResourceManager.GetString("TeamLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Selection.
        /// </summary>
        public static string TeamSelection {
            get {
                return ResourceManager.GetString("TeamSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TSI.
        /// </summary>
        public static string TotalSkillIndex {
            get {
                return ResourceManager.GetString("TotalSkillIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upcoming Matches.
        /// </summary>
        public static string UpcomingMatches {
            get {
                return ResourceManager.GetString("UpcomingMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User:.
        /// </summary>
        public static string UserLabel {
            get {
                return ResourceManager.GetString("UserLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}/week.
        /// </summary>
        public static string WeeklySalary {
            get {
                return ResourceManager.GetString("WeeklySalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winger.
        /// </summary>
        public static string Winger {
            get {
                return ResourceManager.GetString("Winger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arena Details.
        /// </summary>
        public static string XmlFileType_ArenaDetails {
            get {
                return ResourceManager.GetString("XmlFileType_ArenaDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Avatars.
        /// </summary>
        public static string XmlFileType_Avatars {
            get {
                return ResourceManager.GetString("XmlFileType_Avatars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hall Of Fame Players.
        /// </summary>
        public static string XmlFileType_HallOfFamePlayers {
            get {
                return ResourceManager.GetString("XmlFileType_HallOfFamePlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager Compendium.
        /// </summary>
        public static string XmlFileType_ManagerCompendium {
            get {
                return ResourceManager.GetString("XmlFileType_ManagerCompendium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match Details.
        /// </summary>
        public static string XmlFileType_MatchDetails {
            get {
                return ResourceManager.GetString("XmlFileType_MatchDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matches.
        /// </summary>
        public static string XmlFileType_Matches {
            get {
                return ResourceManager.GetString("XmlFileType_Matches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players.
        /// </summary>
        public static string XmlFileType_Players {
            get {
                return ResourceManager.GetString("XmlFileType_Players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Avatars.
        /// </summary>
        public static string XmlFileType_StaffAvatars {
            get {
                return ResourceManager.GetString("XmlFileType_StaffAvatars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff List.
        /// </summary>
        public static string XmlFileType_StaffList {
            get {
                return ResourceManager.GetString("XmlFileType_StaffList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Details.
        /// </summary>
        public static string XmlFileType_TeamDetails {
            get {
                return ResourceManager.GetString("XmlFileType_TeamDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World Details.
        /// </summary>
        public static string XmlFileType_WorldDetails {
            get {
                return ResourceManager.GetString("XmlFileType_WorldDetails", resourceCulture);
            }
        }
    }
}
