//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hyperar.HPA.Globalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hyperar.HPA.Globalization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        public static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggressiveness.
        /// </summary>
        public static string Aggressiveness {
            get {
                return ResourceManager.GetString("Aggressiveness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agreeability.
        /// </summary>
        public static string Agreeability {
            get {
                return ResourceManager.GetString("Agreeability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorize.
        /// </summary>
        public static string Authorize {
            get {
                return ResourceManager.GetString("Authorize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorized.
        /// </summary>
        public static string Authorized {
            get {
                return ResourceManager.GetString("Authorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once you have pasted the Verification Code, click on &apos;Authorize&apos;..
        /// </summary>
        public static string AuthorizeMessage {
            get {
                return ResourceManager.GetString("AuthorizeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookings.
        /// </summary>
        public static string Bookings {
            get {
                return ResourceManager.GetString("Bookings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Career Goals.
        /// </summary>
        public static string CareerGoals {
            get {
                return ResourceManager.GetString("CareerGoals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Career Hattricks.
        /// </summary>
        public static string CareerHattricks {
            get {
                return ResourceManager.GetString("CareerHattricks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once you have logged in into your Hattrick account, you will be provided with a Verification Code. Copy the code and paste it below, making sure there&apos;s no blank spaces at the beggining or the end of the code..
        /// </summary>
        public static string CopyAndPasteVerificationCodeMessage {
            get {
                return ResourceManager.GetString("CopyAndPasteVerificationCodeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cup Goals.
        /// </summary>
        public static string CupGoals {
            get {
                return ResourceManager.GetString("CupGoals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De-authorize.
        /// </summary>
        public static string Deauthorize {
            get {
                return ResourceManager.GetString("Deauthorize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If at any point you want to de-authorize Hattrick Pro Assistant, you can do so by clicking on &apos;De-authorize&apos;..
        /// </summary>
        public static string DeAuthorizeMessage {
            get {
                return ResourceManager.GetString("DeAuthorizeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defending.
        /// </summary>
        public static string Defending {
            get {
                return ResourceManager.GetString("Defending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience.
        /// </summary>
        public static string Experience {
            get {
                return ResourceManager.GetString("Experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form.
        /// </summary>
        public static string Form {
            get {
                return ResourceManager.GetString("Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friendly Goals.
        /// </summary>
        public static string FriendlyGoals {
            get {
                return ResourceManager.GetString("FriendlyGoals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals On Team.
        /// </summary>
        public static string GoalsOnTeam {
            get {
                return ResourceManager.GetString("GoalsOnTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health.
        /// </summary>
        public static string Health {
            get {
                return ResourceManager.GetString("Health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Honesty.
        /// </summary>
        public static string Honesty {
            get {
                return ResourceManager.GetString("Honesty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keeper.
        /// </summary>
        public static string Keeper {
            get {
                return ResourceManager.GetString("Keeper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lastname.
        /// </summary>
        public static string Lastname {
            get {
                return ResourceManager.GetString("Lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leadership.
        /// </summary>
        public static string Leadership {
            get {
                return ResourceManager.GetString("Leadership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to League Goals.
        /// </summary>
        public static string LeagueGoals {
            get {
                return ResourceManager.GetString("LeagueGoals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loyalty.
        /// </summary>
        public static string Loyalty {
            get {
                return ResourceManager.GetString("Loyalty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matches.
        /// </summary>
        public static string Matches {
            get {
                return ResourceManager.GetString("Matches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matches On Team.
        /// </summary>
        public static string MatchesOnTeam {
            get {
                return ResourceManager.GetString("MatchesOnTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MC Bonus.
        /// </summary>
        public static string MotherclubBonus {
            get {
                return ResourceManager.GetString("MotherclubBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nickname.
        /// </summary>
        public static string Nickname {
            get {
                return ResourceManager.GetString("Nickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Authorized.
        /// </summary>
        public static string NotAuthorized {
            get {
                return ResourceManager.GetString("NotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Authorization Web Page.
        /// </summary>
        public static string OpenAuthorizationWebPage {
            get {
                return ResourceManager.GetString("OpenAuthorizationWebPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to use Hattrick Pro Assistant, you have to authorize it first. Click on &apos;Open Authorization Web Page&apos; to begin the authorization process..
        /// </summary>
        public static string OpenAuthorizationWebPageMessage {
            get {
                return ResourceManager.GetString("OpenAuthorizationWebPageMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        public static string Parameters {
            get {
                return ResourceManager.GetString("Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passing.
        /// </summary>
        public static string Passing {
            get {
                return ResourceManager.GetString("Passing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions.
        /// </summary>
        public static string Permissions {
            get {
                return ResourceManager.GetString("Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playmaking.
        /// </summary>
        public static string Playmaking {
            get {
                return ResourceManager.GetString("Playmaking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        public static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary.
        /// </summary>
        public static string Salary {
            get {
                return ResourceManager.GetString("Salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scoring.
        /// </summary>
        public static string Scoring {
            get {
                return ResourceManager.GetString("Scoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Pieces.
        /// </summary>
        public static string SetPieces {
            get {
                return ResourceManager.GetString("SetPieces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #.
        /// </summary>
        public static string ShirtNumber {
            get {
                return ResourceManager.GetString("ShirtNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialty.
        /// </summary>
        public static string Specialty {
            get {
                return ResourceManager.GetString("Specialty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stamina.
        /// </summary>
        public static string Stamina {
            get {
                return ResourceManager.GetString("Stamina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 1.
        /// </summary>
        public static string StepOne {
            get {
                return ResourceManager.GetString("StepOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 3.
        /// </summary>
        public static string StepThree {
            get {
                return ResourceManager.GetString("StepThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 2.
        /// </summary>
        public static string StepTwo {
            get {
                return ResourceManager.GetString("StepTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Selection.
        /// </summary>
        public static string TeamSelection {
            get {
                return ResourceManager.GetString("TeamSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TSI.
        /// </summary>
        public static string TotalSkillIndex {
            get {
                return ResourceManager.GetString("TotalSkillIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winger.
        /// </summary>
        public static string Winger {
            get {
                return ResourceManager.GetString("Winger", resourceCulture);
            }
        }
    }
}
